# Generated by Django 2.0 on 2017-12-26 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Meas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Plate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_id', models.CharField(max_length=50)),
                ('plate_sn', models.CharField(max_length=50)),
                ('plate_mfr', models.CharField(max_length=50)),
                ('plate_wid', models.IntegerField()),
                ('plate_len', models.IntegerField()),
                ('cust_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Moody.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Verif',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verif_date', models.DateTimeField(verbose_name='date performed')),
                ('verif_foot', models.IntegerField()),
                ('verif_NS', models.IntegerField()),
                ('verif_EW', models.IntegerField()),
                ('verif_top', models.FloatField()),
                ('verif_bot', models.FloatField()),
                ('verif_start', models.FloatField()),
                ('verif_end', models.FloatField()),
                ('verif_rep', models.IntegerField()),
                ('verif_flat', models.IntegerField()),
                ('verif_grade', models.CharField(max_length=4)),
                ('plate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Moody.Plate')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='verif_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Moody.Verif'),
        ),
        migrations.AddField(
            model_name='meas',
            name='profile_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Moody.Profile'),
        ),
        migrations.AlterUniqueTogether(
            name='profile',
            unique_together={('profile_id', 'verif_id')},
        ),
        migrations.AlterUniqueTogether(
            name='plate',
            unique_together={('plate_id', 'cust_id')},
        ),
        migrations.AlterUniqueTogether(
            name='meas',
            unique_together={('id', 'profile_id')},
        ),
    ]
