# Generated by Django 2.0 on 2017-12-27 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Moody', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='verif',
            name='verif_north',
            field=models.IntegerField(default=4),
        ),
    ]
