# Generated by Django 2.0 on 2017-12-28 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Moody', '0002_verif_verif_north'),
    ]

    operations = [
        migrations.AddField(
            model_name='verif',
            name='verif_diag',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='verif',
            name='verif_len',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='verif',
            name='verif_wid',
            field=models.IntegerField(default=8),
            preserve_default=False,
        ),
    ]
