# Generated by Django 2.0 on 2017-12-29 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Moody', '0004_meas_verif_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='meas',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='profile',
            unique_together=set(),
        ),
    ]
