# Generated by Django 2.0 on 2017-12-29 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Moody', '0005_auto_20171229_0015'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='plate',
            unique_together=set(),
        ),
    ]
