# Generated by Django 2.0 on 2017-12-31 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Moody', '0006_auto_20171229_0035'),
    ]

    operations = [
        migrations.AddField(
            model_name='verif',
            name='clos_7',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='verif',
            name='clos_8',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='verif',
            name='verif_cert',
            field=models.TextField(default=100110000, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='verif',
            name='verif_descr',
            field=models.TextField(default='Initial', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='verif',
            name='verif_tech',
            field=models.TextField(default='As Found, Left As Found', max_length=50),
            preserve_default=False,
        ),
    ]
